apiVersion: v1
kind: ConfigMap
metadata:
  name: riotwebconfig
data:
  config.json: |
    {
        "default_server_config": {
            "m.homeserver": {
                "base_url": "https://synapse.sunsingerus.com",
                "server_name": "synapse.sunsingerus.com"
            },
            "m.identity_server": {
                "base_url": "https://vector.im"
            }
        },
        "disable_custom_urls": true,
        "disable_guests": false,
        "disable_login_language_selector": false,
        "disable_3pid_login": false,
        "brand": "ISPRAS",
        "integrations_ui_url": "https://scalar.vector.im/",
        "integrations_rest_url": "https://scalar.vector.im/api",
        "integrations_widgets_urls": [
            "https://scalar.vector.im/_matrix/integrations/v1",
            "https://scalar.vector.im/api",
            "https://scalar-staging.vector.im/_matrix/integrations/v1",
            "https://scalar-staging.vector.im/api",
            "https://scalar-staging.riot.im/scalar/api"
        ],
        "integrations_jitsi_widget_url": "https://scalar.vector.im/api/widgets/jitsi.html",
        "bug_report_endpoint_url": "https://riot.im/bugreports/submit",
        "defaultCountryCode": "RU",
        "showLabsSettings": false,
        "features": {
            "feature_pinning": "labs",
            "feature_custom_status": "labs",
            "feature_custom_tags": "labs",
            "feature_state_counters": "labs"
        },
        "default_federate": true,
        "default_theme": "light",
        "roomDirectory": {
            "servers": [
                "synapse.sunsingerus.com"
            ]
        },
        "welcomeUserId": "@riot-bot:synapse.sunsingerus.com",
        "piwik": {
            "url": "https://piwik.riot.im/",
            "whitelistedHSUrls": ["https://matrix.org"],
            "whitelistedISUrls": ["https://vector.im", "https://matrix.org"],
            "siteId": 1
        },
        "enable_presence_by_hs_url": {
            "https://matrix.org": false
        }
    }

