apiVersion: v1
kind: Pod
metadata:
  name: riotweb
  labels:
    app: riotweb
spec:
  containers:
    - name: riotweb
      image: vectorim/riot-web
      ports:
        - containerPort: 80
      volumeMounts:
        - name: config-volume
          mountPath: /app/config.json
          subPath: config.json
    - name: sh
      image: busybox
      command:
        - "/bin/sh"
        - "-c"
        - "--"
      args:
        - "while true; do sleep 30; done;"
  volumes:
    - name: config-volume
      configMap:
        name: riotwebconfig
  restartPolicy: Never

